# Generated by Django 2.2 on 2021-01-20 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('avatar', 'title', 'category')},
        ),
    ]
